# Generated by Django 4.2.5 on 2023-09-07 10:05

import core.services.upload_avatar_service
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_avatarmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar_service.upload_avatar),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.profilemodel'),
        ),
        migrations.DeleteModel(
            name='AvatarModel',
        ),
    ]
