# Generated by Django 4.2.4 on 2023-08-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
